name: Server Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run formatter
        run: npm run format
      - name: Run tests
        run: npm run test
